DISTMYSQL-197 version option does not return easily understandable version number
percona/orchestrator-packaging pull request #5
Opened 2022-07-19 07:51 UTC by adivinho

<img width="946" alt="Screenshot 2022-07-19 at 10 49 48" src="https://user-images.githubusercontent.com/25184101/179696605-2fb9fcfc-4174-4e9d-8e3e-4300b34c4ffc.png">

2022-07-19 13:44 UTC, EvgeniyPatlan requested changes

2022-07-19 13:44 UTC, EvgeniyPatlan commented on orchestrator_builder.sh
> +    description="$(git rev-parse HEAD)"
in case we prepare packages the git files might be removed so we need to be able to pass version from env variable

2022-07-20 20:00 UTC, adivinho commented on orchestrator_builder.sh
> +    description="$(git rev-parse HEAD)"
<img width="847" alt="Screenshot 2022-07-19 at 18 11 04" src="https://user-images.githubusercontent.com/25184101/180071001-c88d1dfd-7cb3-41fd-ae2b-1730fe59c34f.png">

2022-07-22 07:38 UTC, vorsel approved these changes

2022-07-22 07:39 UTC, merged